# Generated by Django 4.2.2 on 2024-06-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_status',
            field=models.CharField(choices=[('create', 'Создана'), ('started', 'Запущена'), ('done', 'Завершена')], default='create', max_length=50, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='regularity',
            field=models.CharField(choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'раз в месяц')], max_length=50, verbose_name='переодичность'),
        ),
        migrations.AlterField(
            model_name='trymailing',
            name='status',
            field=models.CharField(choices=[('success', 'Успешно'), ('fail', 'Не успешно')], default='', max_length=50, verbose_name='статус'),
        ),
    ]
