# Generated by Django 4.2.2 on 2024-06-18 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mailing_mailing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='конец рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='next_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='следующая дата отправки'),
        ),
        migrations.AddField(
            model_name='trymailing',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='клиент рассылки'),
        ),
        migrations.AddField(
            model_name='trymailing',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mailing', verbose_name='рассылка'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='начало рассылки'),
        ),
    ]
